name: Delete branch from destination repository
on:
  delete
env:
  DEST_REPO: michaltc/workspace-microapps-bundles
  DEST_REPO_DIR: ../workspace-microapps-bundles
  BUNDLES_DIR: bundles
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout destination repository
        uses: actions/checkout@v1
        with:
          repository: ${{ env.DEST_REPO }}
          ref: master

      - name: Delete destination branch
        run: |
          set -x
          cd $DEST_REPO_DIR

          git config user.name "Bundlegen bot"
          git config user.email "bundlegen.bot@github.com"
          git remote set-url origin "git@github.com:$DEST_REPO.git"

          set +x
          mkdir -p "$HOME/.ssh/"
          echo "${{ secrets.DEST_REPO_SSH_KEY }}" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"
          set -x

          ssh-keyscan -H -t rsa github.com >> ~/.ssh/known_hosts
          git push origin --delete "${GITHUB_REF:11}" || true
          rm "$HOME/.ssh/id_rsa"
